### ISSUE TITLE
TypeError readInt64BE is not a function

### ISSUE THREAD

**Issue by hutorny** [liteserver/binn.js#2]
Reading an Int64 value fails with error
```
TypeError: this.buffer.readInt64BE is not a function
    at Decoder.parse (node_modules/binn.js/binn.js:246:25)
    at Decoder.list (node_modules/binn.js/binn.js:127:21)
    at Decoder.parse (node_modules/binn.js/binn.js:183:17)
    at Decoder.obj (node_modules/binn.js/binn.js:147:23)
    at Decoder.parse (node_modules/binn.js/binn.js:193:17)
    at Object.decode (node_modules/binn.js/binn.js:289:23)

```
NodeJS version:
```
$ nodejs --version
v10.10.0
```
OS version:

```
uname -a
Linux deb9 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
```

**Comment by kroggen** [comment]
Hi Eugene,

Indeed, javascript does not have native support for 64 bit integers.

If you have some solution, feel free to contribute.

Peace!

**Comment by hutorny** [comment]
Hi Bernardo,

This works for me, perhaps it may work for others too:
```
const Int64BE = require("int64-buffer").Int64BE; 
Buffer.prototype.readInt64BE || (Buffer.prototype.readInt64BE = function(offset) {
	var buffer = this.slice(offset);
	return new Int64BE(buffer);
});

```

**Comment by kroggen** [comment]
Thank you!

I will review its usage when I have time.

You can send a PR if you want.

**Comment by ghost** [comment]
readBigUInt64BE() is the function name

const buf = Buffer.from([11, 11, 11, 11, 11, 20, 11, 11])
console.log(buf);
console.log(buf.readBigUInt64BE());

readBigUInt64BE() will return BigInt
